version: 0.2

env:
  shell: /bin/sh
        
phases:
  pre_build:
    commands:
      - ls -la 
  build:
    commands:
      - npm ci
      - npm install -g gulp
      - gulp build
artifacts:
  files:
    - dist/*
